# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- name: Apply ACLs to PAN Firewalls
  hosts: panos
  connection: local
  gather_facts: False
  vars:
    erase: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/pan_credentials.yml
    - ./credentials/servicenow_credentials.yml
    - ./vars/acl_entries.yml
  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:

    - block:
      - name: Add an ACL entry
        panos_security_rule:
          ip_address: "{{ ansible_host }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          rule_name: "{{item.rule_name}}"
          description: "{{item.rule_name}}"
          source_ip: "{{item.source_ip}}"
          destination_ip: "{{ item.destination_ip }}"
          source_zone: "['{{item.source_zone}}']"
          destination_zone: "['{{item.destination_zone}}']"
          action: "{{ item.action}}"
          state: present
        loop: "{{ acl_entries }}"
        ignore_errors: True
      when: not erase|bool

    - block:
      - name: Remove ACL entries
        panos_security_rule:
          ip_address: "{{ ansible_host }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          rule_name: "{{item.rule_name}}"
          state: absent
        loop: "{{ acl_entries }}"

      - name: Open Ticket in SNOW
        snow_record:
          table: incident
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
          instance: "{{ SN_INSTANCE }}"
          state: present
          data:
            short_description: "PAN ACLs REMOVED"
      when: erase|bool
