# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- name: Confirm presence of ACLs on PAN Firewalls
  hosts: panos
  connection: local
  gather_facts: False
  vars:
    erase: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/pan_credentials.yml
    - ./vars/acl_entries.yml
  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:

    - name: Query ACL IP Rules
      uri:
        url: https://{{ ansible_host }}/restapi/9.0/Policies/SecurityRules?location=vsys&vsys={{ vsys }}
        method: GET
        user: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"
        method: GET
        headers:
          Accept: "application/json"
        force_basic_auth: yes
        body_format: json
        return_content: yes
        validate_certs: False
      register: security_rule_output


    - name: Print Security Rules
      debug:
        var: security_rule_output.json

    - name: Print Security Rule Names
      debug:
        msg: "{{ msg.split('\n') }}"
      vars:
        msg: |
          The RULE NAME is {{ item.description }}
          The DESTINATION ZONE is {{ item.destination.member[0] }}
          The ACTION is {{ item.action }}
      loop: "{{security_rule_output.json.result.entry}}"
      loop_control:
        label: "{{ item.description }}"

      # The SOURCE IP ADDRESS is {{ item.action }}
      # The DESTINATION IP ADDRESS is {{ item.action }}
      # The SOURCE IP ZONE is {{ item.action }}
