# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- name: Delete ACL entry Request
  hosts: webserver
  gather_facts: False

  tasks:
    - name: Check to see if acl_entries.csv exists
      stat:
        path: "/home/{{ ansible_user }}/csvfiles/acl_entries.csv"
      register: acl_entries_output

    - name: Delete specified ACL entry.
      lineinfile:
        path: "/home/{{ ansible_user }}/csvfiles/acl_entries.csv"
        regexp: "{{rule_name}}*"
        state: absent
      when: acl_entries_output.stat.exists == True

- name: Update ACL to apply HTML Page
  hosts: webserver
  gather_facts: False
  vars:
    csvfile: "{{ lookup('file', '{{ playbook_dir }}/csvfiles/acl_entries.csv') }}"

    - name: Check to see if acl_entries_to_apply.html exists
      stat:
        path: "/home/www/html/acl_entries_to_apply.html"
      register: acl_entries_to_apply_output
      become: yes

    - name: Delete acl_entries_to_apply.html if it does exist
      file:
        path: "/home/www/html/acl_entries_to_apply.html"
        state: absent
      when: acl_entries_output.stat.exists == True
      become: yes

    - name: Create acl_entries_to_apply.html
      template:
        src: "{{ playbook_dir }}/templates/acl_entries_to_apply.j2"
        dest: "/home/www/html/acl_entries_to_apply.html"
      become: yes
