# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- name: Delete ACL entry Request
  hosts: webserver
  gather_facts: False

  tasks:
    - name: Check to see if acl_entries.csv exists
      stat:
        path: "/home/{{ ansible_user }}/csvfiles/acl_entries.csv"
      register: acl_entries_output

    - name: Delete specified ACL entry.
      lineinfile:
        path: "/home/{{ ansible_user }}/csvfiles/acl_entries.csv"
        regexp: "{{rule_name}}*"
        state: absent
      when: acl_entries_output.stat.exists == True
