# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    erase: false
  vars_files:
    - default_vars.yml
    - ./credentials/pan_credentials.yml
    - ./vars/pan_mgmt_ips.yml
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:

    - block:
      - name: add zone trust
        panos_zone:
          ip_address: "{{ item }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: trust
          mode: layer3
          state: present
        loop: "{{ pan_mgmt_ips }}"

      - name: add zone untrust
        panos_zone:
          ip_address: "{{ item }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: untrust
          mode: layer3
          state: present
        loop: "{{ pan_mgmt_ips }}"
      when: not erase|bool

    - block:
      - name: remove zone trust
        panos_zone:
          ip_address: "{{ item }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: trust
          mode: layer3
          state: absent
        loop: "{{ pan_mgmt_ips }}"

      - name: remove zone untrust
        panos_zone:
          ip_address: "{{ item }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: untrust
          mode: layer3
          state: absent
        loop: "{{ pan_mgmt_ips }}"
      when: erase|bool
