# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict

---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - default_vars.yml
    - ./credentials/pan_credentials.yml
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    # - name: include variables (free-form)
    #   include_vars: vars.yml
    #   no_log: 'yes'

    - name: add a rule to allow HTTP
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"
        operation: 'add'
        rule_name: 'Web traffic'
        application: 'web-browsing'
        description: 'Allow HTTP traffic'
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'allow'
        commit: "False"

    - name: SSH Inbound
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"
        operation: 'add'
        rule_name: 'SSH traffic'
        application: ['ping','ssh']
        description: 'Allow SSH traffic'
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'allow'
        commit: "False"

    - name: allow all rule
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"
        operation: 'add'
        rule_name: 'allow-out-all'
        application: 'any'
        description: 'allow all outbound'
        source_zone: ['trust']
        destination_zone: ['untrust']
        action: 'allow'
        commit: "False"

    - name: Log default deny
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"
        operation: 'add'
        rule_name: 'Log default deny'
        description: 'Allow SSH traffic'
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'deny'
        commit: "True"
