# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks

---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - default_vars.yml
    - ./credentials/pan_credentials.yml
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: add zone trust
      panos_zone:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"
        zone: trust
        mode: layer3
        state: present

    - name: add zone untrust
      panos_zone:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ PAN_USERNAME }}"
        password: "{{ PAN_PASSWORD }}"
        zone: untrust
        mode: layer3
        state: present
